version: "3.8"
services:
  api:
    build: ./1 - python
    ports:
      - "8000:8000"
    volumes:
      - ./1 - python:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  tests:
    build: ./1 - python
    volumes:
      - ./1 - python:/app
    command: pytest -v tests/test_alunos.py
